### ISSUE TITLE
[Management] GetOfferByID - NumberFormatException

### ISSUE THREAD

**Issue by ScottWalkerAU** [SENG3150Connections/Project#18]
**File:** Management.Actions.GetOfferByID.java
**Line:** 36
**Issue:**
java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at org.jooq.types.UInteger.valueOf(UInteger.java:199)
	at NewcastleConnections.Management.Actions.GetOfferByID.execute(GetOfferByID.java:36)

java.lang.NumberFormatException: Value is out of range : -1
	at org.jooq.types.UInteger.rangeCheck(UInteger.java:259)
	at org.jooq.types.UInteger.valueOf(UInteger.java:199)
	at NewcastleConnections.Management.Actions.GetOfferByID.execute(GetOfferByID.java:36)

**Suggested Solution:**
Add NumberFormatException to a new catch() block and return ERROR, without calling printStackTrace

**Comment by Freakout2114** [comment]
**Fixed** - Added a try catch block around the query that will throw a `NumberFormatException `and return `ERROR`
